# Generated by Django 4.2.29 on 2026-03-17 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_first_name", models.CharField(max_length=150)),
                ("customer_last_name", models.CharField(max_length=150)),
                ("customer_email", models.EmailField(max_length=254, unique=True)),
                ("customer_password", models.CharField(max_length=128)),
                ("location_enabled", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "Customer",
            },
        ),
    ]
