# Generated by Django 4.2.29 on 2026-03-24 20:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customer_google_auth_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business_id', models.OneToOneField(db_column='business_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('business_email', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=255)),
                ('business_owner_first_name', models.CharField(max_length=150)),
                ('business_owner_last_name', models.CharField(max_length=150)),
                ('business_description', models.CharField(blank=True, default='', max_length=500)),
                ('business_address', models.CharField(blank=True, default='', max_length=255)),
                ('google_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('auth_provider', models.CharField(default='local', max_length=20)),
            ],
            options={
                'db_table': 'Business',
            },
        ),
    ]
