# Generated by Django 4.2.29 on 2026-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='business_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
