# Generated by Django 4.2.29 on 2026-04-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="notifications_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
