# Generated by Django 4.2.29 on 2026-03-24 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_business_business_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_owner_first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_owner_last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
